In [ ]:
##Question 01:Use numpy to create a 3×3 matrix of random integers between 1 and 50.
import numpy as np

random_matrix = np.random.randint(1, 50, (3, 3))
print("Random 3×3 Matrix:\n", random_matrix)

Random 3×3 Matrix:
 [[ 9 10  1]
 [43 41 37]
 [17 37 48]]


In [ ]:
##Question 02:With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.

# Set seed for reproducibility
np.random.seed(10)
seeded_matrix = np.random.randint(1, 50, (3, 3))
print("Matrix With Fixed Seed:\n", seeded_matrix)

Matrix With Fixed Seed:
 [[10 37 16]
 [ 1 29 26]
 [30 49 30]]


In [ ]:
##Question 03:Without setting a seed, allowing random values to change each time.

np.random.seed(None)
non_seeded_matrix = np.random.randint(1, 50, (3, 3))
print("Random Matrix Without Seed:\n", non_seeded_matrix)

Random Matrix Without Seed:
 [[ 4 10 37]
 [45 35 10]
 [44  8 21]]




## Explanation of the Codes:
**For Question 01:**
01. This imports the NumPy library, which is used for numerical computing.
02. np.random.randint(1, 50, (3, 3)) generates a 3×3 matrix with random integers.
03. 1 is the inclusive lower bound.
04. 50 is the exclusive upper bound.
05. (3, 3) specifies the matrix size.
06. Displays the generated 3×3 matrix on the screen.

**For Question 02:**
01. np.random.seed(10) - random seed to 10, ensuring that the same random numbers are generated each time the code is run.
02. Since the seed is fixed, this matrix will always be the same every time you run the code.

**For Question 03:**
01. np.random.seed(None) - This ensures that the random number generator uses a new random starting point every time the code runs.
02. Since no fixed seed is set, the numbers will change every time you run the code.

## **Difference Between The Two Output**
01. Reproducibility:
Seeded: Output is reproducible and consistent across runs.
Non-Seeded: Output is not reproducible and changes every time.
02. Randomness:
Seeded: The sequence of random numbers is deterministic.
Non-Seeded: The sequence of random numbers is truly random.
03. Use Cases:
Seeded: Used when consistent results are needed.
Non-Seeded: Used when variability is required.